USE perpage;
DROP TABLE IF EXISTS contact;

CREATE TABLE contact (
  id INT AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  mail VARCHAR(100) NOT NULL,
  msg MEDIUMTEXT NOT NULL,
  CONSTRAINT id_contact PRIMARY KEY(id)
);