export type {default as Contact} from './Contact'
export type {default as Picture} from './Picture'
export type {default as Link} from './Link'
export type {default as Project} from './Project'
export type {default as Skill} from './Skill'
